tools:
    # external_code_coverage: true
    php_mess_detector: true
    php_code_sniffer: true
    sensiolabs_security_checker: true
    # php_code_coverage: true
    php_pdepend: true
    php_loc:
        enabled: true
        excluded_dirs: [vendor, tests]
filter:
    excluded_paths:
        - 'tests/*'
build:
    environment:
              php:
                  version: 5.6.9       # Common versions: 5.4, 5.5, 5.6, 7.0 or hhvm
    tests:
        override:
            -
                command: phpunit --coverage-clover=package-coverage-file
                coverage:
                    file: package-coverage-file
                    format: php-clover